---
- hosts: all
  vars:
    ansible_user: azureuser
    ansible_password: P@ssw0rd12344321
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:
  - name: Install IIS
    win_feature:
        name: web-server 
        include_management_tools: yes 
        include_sub_features: yes
        state: present
  - name: Create logging directory 
    win_file:
        path: c:\logging 
        state: directory